module.exports = {
    CellRef:[
        {
            no:0,
            width:640,
            height:250,
            top:0,
            left:0
        },
        {
            no:1,
            width:320,
            height:250,
            top:250,
            left:0
        },
        {
            no:2,
            width:320,
            height:250,
            top:250,
            left:320
        },
        {
            no:3,
            width:320,
            height:250,
            top:0,
            left:640
        },
        {
            no:4,
            width:320,
            height:250,
            top:250,
            left:640
        },
        {
            no:5,
            width:320,
            height:500,
            top:0,
            left:960
        }
    ]
}