module.exports = {
    CellRef:[
        {
            no:0,
            width:800,
            height:300,
            top:0,
            left:0
        },
        {
            no:1,
            width:400,
            height:300,
            top:300,
            left:0
        },
        {
            no:2,
            width:400,
            height:300,
            top:300,
            left:400
        },
        {
            no:3,
            width:400,
            height:300,
            top:0,
            left:800
        },
        {
            no:4,
            width:400,
            height:300,
            top:300,
            left:800
        },
        {
            no:5,
            width:400,
            height:600,
            top:0,
            left:1200
        }
    ]
}